apiVersion: v1
kind: Pod
metadata:
  name: lumpy-koala
  labels:
    name: lumpy-koala
spec:
  containers:
  - name: base-container
    image: busybox
    command: ['sh', '-c', 'if [ -f /workdir/eager.txt ]; then sleep 99999; else exit; fi']
    volumeMounts:
    - name: workdir-volume
      mountPath: /workdir
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh','-c','touch /workdir/eager.txt']
    volumeMounts:
    - name: workdir-volume
      mountPath: /workdir
  volumes:
  - name: workdir-volume
    emptyDir: {}